#!/usr/bin/env zsh
sketchybar	--set	bird background.padding_right=14

sketchybar	--set	spotify_playlist background.padding_left=16

sketchybar 	--set   front_app script="$PLUGIN_DIR/front_app.sh 25"

