#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"
MAIN_DISPLAY=$(system_profiler SPDisplaysDataType | grep -B 3 'Main Display:' | awk '/Display Type/ {print $3}')

source "$SKETCHYBAR_CONFIG/sketchybarrc-base"
if [ $MAIN_DISPLAY = "Built-in" ]; then
    source "$SKETCHYBAR_CONFIG/sketchybarrc-laptop"
fi

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
