#!/usr/bin/env zsh

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
FONT_FACE="Hack Nerd Font"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar

sketchybar	--bar \
                height=38 \
                blur_radius=0 \
                position=top \
                sticky=on \
                padding_left=23 \
                padding_right=23 \
                display=main \
                color=0x6624273a

sketchybar	--default \
                updates=when_shown \
                background.color=0xff24273a \
                background.padding_left=2 \
                background.padding_right=2 \
                background.corner_radius=5 \
                background.height=24 \
                icon.color=0xffffffff \
                icon.font="$FONT_FACE:Bold:17.0" \
                icon.padding_left=8 \
                icon.padding_right=7 \
                label.font="$FONT_FACE:Bold:12.0" \
                label.color=0xffcad3f5 \
                label.padding_left=0 \
                label.padding_right=7

sketchybar	--add	item current_space left \
            --set	current_space \
                        background.color=0xff67e8f9 \
                        background.padding_right=5 \
                        icon.font="$FONT_FACE:Bold:13.0" \
                        icon.color=0xff24273a \
                        label.drawing=off \
                        script="$PLUGIN_DIR/current_space.sh" \
            --subscribe current_space space_change mouse.clicked

sketchybar 	--add item front_app left \
            --set   front_app \
                          background.padding_left=0 \
                          background.padding_right=0 \
                          icon.y_offset=0 \
                          icon.color=0xffffffff \
                          label.drawing=no \
                          script="$PLUGIN_DIR/front_app.sh 50" \
          --add item front_app.name left \
          --set front_app.name \
                    icon.drawing=off \
                    label="Hello" \
                    label.drawing=yes

sketchybar --add event window_focus \
           --add event title_change
sketchybar  --add   bracket front_app_bracket \
                    front_app \
                    front_app.name \
            --subscribe	front_app front_app_switched window_focus title_change \

sketchybar	--add	item bird q \
            --set	bird \
                    	background.color=0xaa24273a \
                      background.padding_right=0 \
                      icon= \
                    	icon.color=0xccffffff \
                    	icon.font="$FONT_FACE:Bold:20.0" \
                    	label.drawing=off \
                    	script="$PLUGIN_DIR/bird.sh" \
            --subscribe bird mouse.clicked

sketchybar	--add	item weather q \
            --set	weather \
                    	icon= \
                    	icon.color=0xfff5bde6 \
                        icon.font="$FONT_FACE:Bold:15.0" \
                    	update_freq=1800 \
                    	script="$PLUGIN_DIR/weather.sh" \
            --subscribe weather system_woke

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
sketchybar	--add	item spotify_playlist e \
            --set	spotify_playlist \
                        background.color=0xaa24273a \
                        background.padding_left=0 \
                        icon=󰲸 \
                        icon.color=0xffc6a0f6 \
                        icon.font="$FONT_FACE:Bold:22.0" \
                        label.drawing=off \
                        script="$PLUGIN_DIR/spotify_playlist.sh" \
            --subscribe spotify_playlist mouse.clicked

sketchybar  --add   event spotify_change $SPOTIFY_EVENT \
            --add   item spotify e \
            --set   spotify \
                        icon= \
                    	icon.font="$FONT_FACE:Bold:20.0" \
                    	icon.y_offset=1 \
                        label.drawing=off \
                    	label.padding_left=2 \
                        script="$PLUGIN_DIR/spotify.sh" \
            --subscribe spotify spotify_change mouse.clicked

sketchybar  --add   item clock right \
            --set   clock \
                        icon= \
                        icon.y_offset=1 \
                        icon.color=0xffed8796 \
                        update_freq=10 \
                        script="$PLUGIN_DIR/clock.sh"

sketchybar  --add   item battery right \
            --set   battery \
                        icon.y_offset=1 \
                        update_freq=10 \
                        script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke

